LIBSOURCES=""
LIBOBJECTS=""

LIBSOURCES="$LIBSOURCES Globals.cc "
LIBOBJECTS="$LIBOBJECTS Globals.o "


LIBSOURCES="$LIBSOURCES Logger.cc "
LIBOBJECTS="$LIBOBJECTS Logger.o "

LIBSOURCES="$LIBSOURCES Rect.cc "
LIBOBJECTS="$LIBOBJECTS Rect.o "

LIBSOURCES="$LIBSOURCES Event.cc "
LIBOBJECTS="$LIBOBJECTS Event.o "

LIBSOURCES="$LIBSOURCES BasicEvent.cc "
LIBOBJECTS="$LIBOBJECTS BasicEvent.o "

LIBSOURCES="$LIBSOURCES ChangeEvent.cc "
LIBOBJECTS="$LIBOBJECTS ChangeEvent.o "

LIBSOURCES="$LIBSOURCES CursesException.cc "
LIBOBJECTS="$LIBOBJECTS CursesException.o "

LIBSOURCES="$LIBSOURCES CursesManager.cc "
LIBOBJECTS="$LIBOBJECTS CursesManager.o "

LIBSOURCES="$LIBSOURCES CursesWindow.cc "
LIBOBJECTS="$LIBOBJECTS CursesWindow.o "

LIBSOURCES="$LIBSOURCES ColorAttribute.cc "
LIBOBJECTS="$LIBOBJECTS ColorAttribute.o "

LIBSOURCES="$LIBSOURCES Widget.cc "
LIBOBJECTS="$LIBOBJECTS Widget.o "

LIBSOURCES="$LIBSOURCES FocusableWidget.cc "
LIBOBJECTS="$LIBOBJECTS FocusableWidget.o "

LIBSOURCES="$LIBSOURCES Container.cc "
LIBOBJECTS="$LIBOBJECTS Container.o "

LIBSOURCES="$LIBSOURCES FocusableContainer.cc "
LIBOBJECTS="$LIBOBJECTS FocusableContainer.o "

LIBSOURCES="$LIBSOURCES ContainerFocusManager.cc "
LIBOBJECTS="$LIBOBJECTS ContainerFocusManager.o "

LIBSOURCES="$LIBSOURCES ContainerFocusManaging.cc "
LIBOBJECTS="$LIBOBJECTS ContainerFocusManaging.o "

LIBSOURCES="$LIBSOURCES Label.cc "
LIBOBJECTS="$LIBOBJECTS Label.o "

LIBSOURCES="$LIBSOURCES Button.cc "
LIBOBJECTS="$LIBOBJECTS Button.o "

LIBSOURCES="$LIBSOURCES TextBox.cc "
LIBOBJECTS="$LIBOBJECTS TextBox.o "

LIBSOURCES="$LIBSOURCES TextArea.cc "
LIBOBJECTS="$LIBOBJECTS TextArea.o "

LIBSOURCES="$LIBSOURCES CheckBox.cc "
LIBOBJECTS="$LIBOBJECTS CheckBox.o "

LIBSOURCES="$LIBSOURCES MenuItem.cc "
LIBOBJECTS="$LIBOBJECTS MenuItem.o "

LIBSOURCES="$LIBSOURCES HorizontalMenu.cc "
LIBOBJECTS="$LIBOBJECTS HorizontalMenu.o "

LIBSOURCES="$LIBSOURCES VerticalMenu.cc "
LIBOBJECTS="$LIBOBJECTS VerticalMenu.o "

LIBSOURCES="$LIBSOURCES PopupWindow.cc "
LIBOBJECTS="$LIBOBJECTS PopupWindow.o "

LIBSOURCES="$LIBSOURCES PopupMenu.cc "
LIBOBJECTS="$LIBOBJECTS PopupMenu.o "

LIBSOURCES="$LIBSOURCES RadioButton.cc "
LIBOBJECTS="$LIBOBJECTS RadioButton.o "

LIBSOURCES="$LIBSOURCES Screen.cc "
LIBOBJECTS="$LIBOBJECTS Screen.o "

LIBSOURCES="$LIBSOURCES ScrollPane.cc "
LIBOBJECTS="$LIBOBJECTS ScrollPane.o "

# LIBSOURCES="$LIBSOURCES MessageBox.cc "
# LIBOBJECTS="$LIBOBJECTS MessageBox.o "
# 
# LIBSOURCES="$LIBSOURCES ConfirmBox.cc "
# LIBOBJECTS="$LIBOBJECTS ConfirmBox.o "

LIBSOURCES="$LIBSOURCES MainLoop.cc "
LIBOBJECTS="$LIBOBJECTS MainLoop.o "

LIBSOURCES="$LIBSOURCES Window.cc "
LIBOBJECTS="$LIBOBJECTS Window.o "

LIBSOURCES="$LIBSOURCES SelectBox.cc "
LIBOBJECTS="$LIBOBJECTS SelectBox.o "

LIBSOURCES="$LIBSOURCES Point.cc "
LIBOBJECTS="$LIBOBJECTS Point.o "

LIBSOURCES="$LIBSOURCES RadioGroup.cc "
LIBOBJECTS="$LIBOBJECTS RadioGroup.o "

LIBSOURCES="$LIBSOURCES Table.cc "
LIBOBJECTS="$LIBOBJECTS Table.o "

LIBSOURCES="$LIBSOURCES ColorSet.cc "
LIBOBJECTS="$LIBOBJECTS ColorSet.o "

LIBSOURCES="$LIBSOURCES ColorTheme.cc "
LIBOBJECTS="$LIBOBJECTS ColorTheme.o "
